import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>DogShop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Dog site</h1>
      <h1>Do my commits count now?</h1>
      <h1>Do my commits count now?!!</h1>
      <h1>Third time's the charm??</h1>
        <h1>ffs m0n</h1>
        <h1>it works?!</h1>

      <Image
        width={2000}
        height={1500}
        src="https://images.unsplash.com/photo-1600077106724-946750eeaf3c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1470&q=80"
        alt="dog"
      />
    </div>
  );
}
