import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div className="px-10 mt-60 flex flex-col my-60">
      <Head>
        <title>Dogshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <div>
        <h1 className="text-center mb-12 text-3xl">Welcome to Dogsite</h1>
      </div>
      <div className="mx-auto lg:w-3/5 lg:flex lg:flex-row lg:h-auto">
        <Image
          width={1000}
          height={800}
          className="rounded-tr-md rounded-tl-md h-48 w-full lg:h-auto lg:w-2/5 lg:rouned-bl-md lg:rounded-tr-none"
          src="/images/dog.jpg"
          alt="dog"
        />
        <div className="bg-white p-8 rounded-bl-md rounded-br-md lg:rounded-bl-none lg:rounded-tr-md ">
          <h2 className="text-gray-700 font-semibold ">
            CORGI SOM FAMILJEHUND
          </h2>
          <p className="text-sm text-gray-600 mt-4 ">
            En corgi är ett bra val för många familjer då den gillar barn och
            kan hänga med på många olika aktiviteter. Många hundar som är
            riktigt små fungerar utmärkt i lägenhet. En corgi trivs dock som
            allra bäst om den har tillgång till en liten trädgård där den kan få
            röra sig fritt ibland. Du måste inte ha stor hundvana för att klara
            en corgi. Det räcker långt att vara lyhörd gentemot sin corgi och
            intresserad av att lära sig mer om rasen och om hundar i allmänhet.
          </p>

          <Link passHref href={"/pickadog"}>
            <button className="hover:scale-110 transition duration-500 ease-in-out; mt-2 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded content-center Link">
              Go to pick dog site!
            </button>
          </Link>
        </div>
      </div>
    </div>
  );
}
